In [1]:
import numpy as np


In [7]:
value_iter_vec = np.array([0,0,0])

def transition_func(A, b):

    def transition(x):
        return A @ x + b

    return transition


markov_A = np.array([[0, 0.5, 0], [0.2, 0, 0.3], [0.3, 0.2, 0]])
markov_b = np.array([0, 0.8, 2])



def update_iteration(value_iter_vec, transition_func):
    new_value_vec = transition_func(value_iter_vec)
    return new_value_vec

transition_updater = transition_func(markov_A, markov_b)
new_value = value_iter_vec
for i in range(25):
    print(new_value)
    new_value = update_iteration(new_value, transition_updater)

[0 0 0]
[0.  0.8 2. ]
[0.4  1.4  2.16]
[0.7   1.528 2.4  ]
[0.764  1.66   2.5156]
[0.83    1.70748 2.5612 ]
[0.85374  1.73436  2.590496]
[0.86718   1.7478968 2.602994 ]
[0.8739484  1.7543342  2.60973336]
[0.8771671  1.75770969 2.61305136]
[0.87885484 1.75934883 2.61469207]
[0.87967441 1.76017859 2.61552622]
[0.88008929 1.76059275 2.61593804]
[0.88029637 1.76079927 2.61614534]
[0.88039964 1.76090288 2.61624877]
[0.88045144 1.76095456 2.61630047]
[0.88047728 1.76098043 2.61632634]
[0.88049021 1.76099336 2.61633927]
[0.88049668 1.76099982 2.61634574]
[0.88049991 1.76100306 2.61634897]
[0.88050153 1.76100467 2.61635058]
[0.88050234 1.76100548 2.61635139]
[0.88050274 1.76100589 2.6163518 ]
[0.88050294 1.76100609 2.616352  ]
[0.88050304 1.76100619 2.6163521 ]


In [8]:
1.761/2

0.8805

In [10]:
-2 + 2.616/2

-0.692

In [14]:
value_iter_vec = np.array([0,0,0,0,0,0])
markov_A = np.array([[0, 0.25, 0.25, 0, 0, 0], [0, 0, 0, 0.5, 0, 0], [0, 0.25, 0, 0, 0.25, 0], [0,0,0,0,0,0.5], [0,0,0,0.25,0,0.25],[0,0,0,0,0,0]])
markov_b = np.array([1,1,1,1,1,0])
transition_updater = transition_func(markov_A, markov_b)
new_value = value_iter_vec
for i in range(25):
    print(new_value)
    new_value = update_iteration(new_value, transition_updater)

[0 0 0 0 0 0]
[1. 1. 1. 1. 1. 0.]
[1.5  1.5  1.5  1.   1.25 0.  ]
[1.75   1.5    1.6875 1.     1.25   0.    ]
[1.796875 1.5      1.6875   1.       1.25     0.      ]
[1.796875 1.5      1.6875   1.       1.25     0.      ]
[1.796875 1.5      1.6875   1.       1.25     0.      ]
[1.796875 1.5      1.6875   1.       1.25     0.      ]
[1.796875 1.5      1.6875   1.       1.25     0.      ]
[1.796875 1.5      1.6875   1.       1.25     0.      ]
[1.796875 1.5      1.6875   1.       1.25     0.      ]
[1.796875 1.5      1.6875   1.       1.25     0.      ]
[1.796875 1.5      1.6875   1.       1.25     0.      ]
[1.796875 1.5      1.6875   1.       1.25     0.      ]
[1.796875 1.5      1.6875   1.       1.25     0.      ]
[1.796875 1.5      1.6875   1.       1.25     0.      ]
[1.796875 1.5      1.6875   1.       1.25     0.      ]
[1.796875 1.5      1.6875   1.       1.25     0.      ]
[1.796875 1.5      1.6875   1.       1.25     0.      ]
[1.796875 1.5      1.6875   1.       1.25     0.  